# Generated by Django 4.2.7 on 2025-08-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_add_created_at_to_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, default=None),
            preserve_default=False,
        ),
    ]
