# Generated by Django 4.2.7 on 2025-08-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_add_property_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="bedrooms",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("pending", "Pending"),
                    ("sold", "Sold"),
                    ("rented", "Rented"),
                ],
                default="available",
                max_length=20,
            ),
        ),
    ]
